name: Build Images and Push to Registry
on:
  workflow_dispatch:
  push:
    tags:
      - "@sufle/api@*"
      - "@sufle/cli@*"

jobs:
  build_api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    name: Build and Push API Image
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/@sufle/api@}" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API and Push to Registry
        uses: docker/build-push-action@v5
        with:
          file: ./apps/api/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/gokceno/sufle-api:latest
            ghcr.io/gokceno/sufle-api:${{ steps.version.outputs.VERSION }}

  build_cli:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    name: Build and Push CLI Image
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/@sufle/cli@}" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build CLI and Push to Registry
        uses: docker/build-push-action@v5
        with:
          file: ./apps/cli/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/gokceno/sufle-cli:latest
            ghcr.io/gokceno/sufle-cli:${{ steps.version.outputs.VERSION }}
